name: 'Takumi Guard setup'
description: 'Configure package registries to route through Takumi Guard'
runs:
  using: 'composite'
  steps:
    - uses: flatt-security/setup-takumi-guard-npm@v1
      with:
        bot-id: "BT01KRJ741G9T8KN3Y91SHA5KF1F"
