---
name: Install Dependencies and Build
description: Install dependencies and build

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 18

    - name: cache node_modules
      id: cache_node_modules
      uses: actions/cache@v3
      with:
        path: |
          ./node_modules
          ./**/node_modules
          ./.yarn/cache
          !./node_modules/.cache
          !./**/node_modules/.cache
        key: node-modules-${{ runner.os }}-${{ hashFiles('./**/yarn.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-${{ hashFiles('./**/yarn.lock') }}
          node-modules-${{ runner.os }}-
          node-modules--

    - name: cache and restore "build result"
      id: cache_build_results
      uses: actions/cache@v3
      with:
        path: |
          ./**/dist
          ./**/.nuxt
          ./**/node_modules/.cache/turbo
        key: cache-build-results-${{ runner.os }}-${{ github.sha }}

    - name: install [root] dependencies
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      run: yarn --immutable
      shell: bash

    - name: build
      if: steps.cache_build_results.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash

    # The directories under the example directory do not consider the strictness of yarn.lock

    - name: install [examples/enclosure-vue3] dependencies
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      working-directory: ./examples/enclosure-vue3
      run: yarn
      shell: bash

    - name: install [examples/enclosure-vue2.7] dependencies
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      working-directory: ./examples/enclosure-vue2.7
      run: yarn
      shell: bash

    - name: install [examples/insider-vue3] dependencies
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      working-directory: ./examples/insider-vue3
      run: yarn
      shell: bash

    - name: install [examples/insider-vue2.7] dependencies
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      working-directory: ./examples/insider-vue2.7
      run: yarn
      shell: bash

